eProsima/Discovery-Server

README.md
It's a bufix:
+ In order to prevent asio installation issues on fast THIRDPARTY=ON must be enforced.
+ to enable the log for debugging purposes we must add LOG_LEVEL_INFO=ON on debug builds.
=> Refs 5983: Updates on docs installation section in order to cope with new .repos installation

src/DSManager.cpp
Writer and ReaderDiscoveryInfo structures have changed, thus discovery callbacks update is required.
=> Refs #6019 - Update discovery server to cope with new fast rtps APIs

discovery-server.repos
update of discovery-server.repos, note that vcs doesn't admit any tabs within this file. New repo dependency:
```
foonathan_memory_vendor:
type: git
url: https://github.com/eProsima/foonathan_memory_vendor.git
version: master
```
=> vcs should also download foonathan repo because its a new fastRTPS dependency [#6122]

CMakeLists.txt
Basically we must prevent OpenSSL target from being link if it doesn't exist and so for the include dirs:
```
if(NOT TINYXML2_LIB_NAME)
if(TARGET tinyxml2)
set(TINYXML2_LIB_NAME tinyxml2)
elseif(TARGET tinyxml2::tinyxml2)
set(TINYXML2_LIB_NAME tinyxml2::tinyxml2)  
else()
message(ERROR "Non standard tinyxml2 target name. Please TINYXML2_LIB_NAME to current targets name.")
endif()
endif()
if(TARGET OpenSSL::SSL)
set(OPENSSL_TARGET OpenSSL::SSL)
else()
unset(OPENSSL_TARGET)
unset(OPENSSL_INCLUDE_DIR CACHE)
endif()
```
There is a subtetly here. Because FindOpenSSL uses mark_as_advanced(OPENSSL_INCLUDE_DIR OPENSSL_LIBRARIES) then those variables are automatically promoted to CACHE ones and cannot be unset if CACHE is not specified.
=> Refs #6153 Making openSSL not mandatory 

src/DSManager.cpp
**DSManager.cpp** in its specific parsing uses `eprosima::fastrtps::xmlparser` string names that are not exported. That doesn't represent an issue using fastrtps as a dynamic library because are not exported but creates havoc if using it as static library because then I've a redefinition. I must then change the namespace where these names are defined to avoid collision turning `xmlparser` into `DSxmlparser` for example:
```   
namespace eprosima {
namespace fastrtps {
namespace DSxmlparser {
const char* PROFILES = "profiles";
const char* PROFILE_NAME = "profile_name";
const char* PREFIX = "prefix";
const char* NAME = "name";
const char* META_UNI_LOC_LIST = "metatrafficUnicastLocatorList";
const char* META_MULTI_LOC_LIST = "metatrafficMulticastLocatorList";
const char* TYPES = "types"; …
```
=> Solving redefinition conflict that prevent statically link to fastrtps

include/DI.h, include/IDs.h, src/DI.cpp, src/DSManager.cpp
This PR add a discovery timepstamp, in milliseconds since process start, to all discovered entities. This timestamp is also added to the snapshot XML files as a `discovered_timestamp` attribute of `ptdi`, `publisher`, and `subscriber` tags.
Signed-off-by: EduPonz <eduardoponz@eprosima.com>
=> Add discovery timestamp to snapshots [8131]

include/DI.h, src/DI.cpp, src/DSManager.cpp, test/xml/test_06_EDP_UDP.xml.in
Testing long time discovery on the raspberry farm several issues were discovered with zombie participants, that is, those whose DATA(U[p]) are received before any DATA(U[r|w]) associated with them.
I wonder why it didn't happen before on Windows and Ubuntu, note that endpoints are destroyed before the participant and its messages should be delivered before avoiding zombie participants especially on localhost but we have no guarantee on message order reception.
I realized this case is unlikely. The server delivers the messages to the clients, thus, is fairly
probable they will be delivered in the server received order but that's not guaranteed because PDP and EDP messages don't share writers.
I must modify the Snapshot comparison function to ignore the zombies. That implied the creation of …
=> Improving again Snapshot comparison to avoid another special scenario

include/DSManager.h, src/main.cpp
`feature/discovery-server/unify-test-v2` branch contains the tests for Discovery Server v2.0.
This branch lost backwards compatibility with Fast DDS <2.0.x> and <2.1.x>.
=> Fix backwards compatibility

test/configuration/test_cases/test_22_environment_variable_setup.xml, test/configuration/test_cases/test_23_fast_discovery_server_tool.xml, test/configuration/test_solutions/test_22_environment_variable_setup.snapshot, test/configuration/test_solutions/test_23_fast_discovery_server_tool.snapshot, test/configuration/tests_params.json
Merge after #24 
eProsima/Fast-DDS#1764 changes the default server guid prefix. This PRs addresses the change on affected tests
=> New default prefix

test/CMakeLists.txt
This PR discriminates which tests to generate based on Fast DDS version
Signed-off-by: EduPonz <eduardoponz@eprosima.com>
=> Check Fast DDS version for adding tests [10763]

test/CMakeLists.txt, test/configuration/test_solutions/test_03_single_server_large.snapshot
Print of GUID_t was changed in Fast-DDS. Some test solutions weren't updated. This PR fixes this.
=> Update guids to new format [11847]

src/DiscoveryServerManager.cpp
#59 fix compilation in Ubuntu Jammy, but broke it in Ubuntu Focal. This PR fixes both.
=> [16440] Avoid static_cast on participant name deduction

README.md, examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp, test/CMakeLists.txt, test/configuration/test_cases/test_61_superclient_environment_variable.xml, test/configuration/test_solutions/test_61_superclient_environment_variable.snapshot, test/configuration/tests_params.json
Add a new test case for a feature to define a super client setting a new environment variable ROS_SUPER_CLIENT to true. This environment variable is used in combination with ROS_DISCOVERY_SERVER. 
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/4047
=> [19967] Define a super client by environment variable

examples/HelloWorldExampleDS/HelloWorld.cxx, examples/HelloWorldExampleDS/HelloWorld.h, examples/HelloWorldExampleDS/HelloWorldCdrAux.hpp, examples/HelloWorldExampleDS/HelloWorldCdrAux.ipp, examples/HelloWorldExampleDS/HelloWorldPubSubTypes.cxx, examples/HelloWorldExampleDS/HelloWorldPubSubTypes.h, resources/static_types/HelloWorld.cxx, resources/static_types/HelloWorld.h, resources/static_types/HelloWorldCdrAux.hpp, resources/static_types/HelloWorldCdrAux.ipp, resources/static_types/HelloWorldPubSubTypes.cxx, resources/static_types/HelloWorldPubSubTypes.h
This PR regenerate the example types.
This is needed to introduce the (future) Fast DDS Gen release v3.2.1 changes.
=> [20176] Regenerate Fast DDS docs example types due to Gen release v3.2.1

examples/HelloWorldExampleDS/HelloWorldv1.cxx, examples/HelloWorldExampleDS/HelloWorldv1.h
This PR adds the `v1` types for the `HelloWorldExampleDS` example generated with `Fast DDS Gen 3.2.1`
=> [20176] Add v1 types for the Helloworld example

include/LateJoiner.h, src/DiscoveryServerManager.cpp, src/LateJoiner.cpp
eProsima/Fast-DDS#4640 refactors ReturnCode to comply with OMG DDS specification. This PR updates to be compatible with this change.
=> Update to new ReturnCode_t

examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp
This PR prevents a compilation error when `COMPILE_EXAMPLES` is set to `ON`. `ReturnCode_t` is no longer an enum.
=> Fix Helloworld compilation Error in 30x

include/DiscoveryItem.h, src/DSLog.h.in
This PR adds support for:
* eprosima/Fast-DDS#4546
=> [20568] Adjust for removing all redundant headers from include/fastrtps

test/CMakeLists.txt, test/configuration/test_cases/test_24_backup.xml, test/configuration/test_cases/test_24_backup_1.xml, test/configuration/test_cases/test_26_backup_restore.xml, test/configuration/test_cases/test_26_backup_restore_1.xml, test/configuration/tests_params.json
This PR updates the BACKUP tests, providing more time to let the server process a backup file and ping the corresponding clients.
It also remove the most basic tests from FAIL_TESTS to test the fix implemented in:
- https://github.com/eProsima/Fast-DDS/pull/4740
=> [20936] Change backup restore order

README.md, examples/HelloWorldExampleDS/HelloWorldPubSubTypes.cxx, examples/HelloWorldExampleDS/HelloWorldPubSubTypes.h, examples/HelloWorldExampleDS/HelloWorldPublisher.cpp, examples/HelloWorldExampleDS/HelloWorldServer.cpp, examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp, examples/HelloWorldExampleDS/HelloWorld_main.cpp, include/DiscoveryItem.h, include/DiscoveryServerManager.h, include/LateJoiner.h, resources/static_types/HelloWorldPubSubTypes.cxx, resources/static_types/HelloWorldPubSubTypes.h, src/DiscoveryItem.cpp, src/DiscoveryServerManager.cpp, src/LateJoiner.cpp, src/main.cpp
This PR migrates fastrtps namespace to fastdds.
Related Fast DDS PR:
* https://github.com/eProsima/Fast-DDS/pull/4898
- N/A The added tests pass locally.
- ❌ Changes are backwards compatible. 
- N/A New feature has been documented/Current behavior is correctly described in the documentation.
- N/A Applicable backports have been included in the description.
=> [21129] Migrate fastrtps namespace to fastdds

.github/workflows/nightly-ubuntu-ci.yml, .github/workflows/weekly-ubuntu-ci.yml
Nightly job was failing due to `os-image`-`os-version` name mismatched. 
This PR fixes it, and move `2.6.x` related job to weekly CI
- **N/A** The added tests pass locally.
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation.
- **N/A** Applicable backports have been included in the description.
- N/A Check CI results: changes do not issue any warning.
- N/A Check CI results: failing tests are unrelated with the changes.
=> [21230] Fix nightly job and move 2.6.x to weekly CI

utils/scripts/update_generated_code_from_idl.sh
This PR performs a cherry pick to the commit in master that introduced the utils type generator.
It also introduces some changes (as the possibility to add an argument to the script for CDR generation, related with some CI refactor Fast DDS Gen PRS:)
- https://github.com/eProsima/Fast-DDS-Gen/pull/366
- https://github.com/eProsima/Fast-DDS-Gen/pull/367
- https://github.com/eProsima/Fast-DDS-Gen/pull/368
- https://github.com/eProsima/Fast-DDS-Gen/pull/369
Those PRs need to be updated with the corresponding CDR version:
- Fast DDS Gen 3.3.x (Fast DDS 2.14.x) -> `cdr-both`
- Fast DDS Gen 3.2.x (Fast DDS 2.13.x) -> `cdr-both`
- Fast DDS Gen 2.5.x (Fast DDS 2.10.x) -> `(no arg provided)`
- Fast DDS Gen 2.1.x (Fast DDS 2.6.x) -> `(no arg provided)`
- …
=> [21244] Add utils script for type generation

include/DiscoveryServerManager.h, src/DiscoveryServerManager.cpp
This PR updates the discovery callbacks to the changes introduced by https://github.com/eProsima/Fast-DDS/pull/5052
- __NO__ Changes are backwards compatible. 
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.
- _N/A_ Applicable backports have been included in the description.
=> [21301] Remove `WriterProxyData` from public APIs

include/DiscoveryServerManager.h, src/DiscoveryServerManager.cpp
This PR updates the discovery callbacks to the changes introduced by https://github.com/eProsima/Fast-DDS/pull/5078
- __NO__ Changes are backwards compatible. 
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.
- _N/A_ Applicable backports have been included in the description.
=> [21300] Remove `ReaderProxyData` from public APIs

CMakeLists.txt, RELEASE_SUPPORT.md, resources/xtypes/HelloWorldCdrAux.ipp, resources/xtypes/HelloWorldPubSubTypes.cxx
This PR bumps to v2.0.0
- N/A The added tests pass locally.
- N/A Changes are backwards compatible. 
- N/A New feature has been documented/Current behavior is correctly described in the documentation.
- N/A Applicable backports have been included in the description.
=> [21366] Bump to v2.0.0

test/CMakeLists.txt, test/configuration/test_cases/test_94_tcpv4_custom_guid_transform_locators.xml, test/configuration/test_cases/test_95_tcpv4_cli.xml, test/configuration/test_cases/test_96_tcpv6_cli.xml, test/configuration/test_cases/test_97_tcpv4_env_var.xml, test/configuration/test_cases/test_98_tcpv6_env_var.xml, test/configuration/test_solutions/test_94_tcpv4_custom_guid_transform_locators.snapshot, test/configuration/tests_params.json
This PR includes a test for a bug in which a TCP client connecting to `localhost` is unable to identify the locator of a TCP discovery server with a custom GUID listening on `any`.
Depends on: 
- https://github.com/eProsima/Fast-DDS/pull/5382
@Mergifyio backport 1.2.x
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.
=> [22056] Transform locators using new host_id PID

resources/static_types/HelloWorldv1.cxx, resources/static_types/HelloWorldv1.h
This PR should fix [the weekly build of discovery server in Fast DDS 2.14.x with fastcdr 1.1.x](https://github.com/eProsima/Fast-DDS/actions/runs/12000937419/job/33450975542). Missing `-cdr both` when generated the types in `static_types` folder
- **N/A** The added tests pass locally.
- **N/A* New feature has been documented/Current behavior is correctly described in the documentation.
- **N/A** Applicable backports have been included in the description.
=> [21508] Generate `v1` types for Helloworld type in `resources/static_types`

test/CMakeLists.txt, test/configuration/test_cases/test_87_set_modifies_env_var_A.xml, test/configuration/test_cases/test_87_set_modifies_env_var_B.xml, test/configuration/test_solutions/test_87_set_modifies_env_var_A.snapshot, test/configuration/test_solutions/test_87_set_modifies_env_var_B.snapshot, test/configuration/tests_params.json, test/run_test.py
This PR updated the CLI API calls according to: 
- https://github.com/eProsima/Fast-DDS/pull/5749
It also adds a new test to verify the modification of the remote connection stored by the daemon after a `set` command.
- _N/A_ Changes are backwards compatible. 
- _N/A_ Applicable backports have been included in the description.
=> [23008] Update CLI commands for Easy Mode

.github/workflows/reusable-ubuntu-ci.yml
The `upload-artifacts` github action do not preserve executable permissions. `fastddds-discovery-server` symlink permissions are also packed with read-only. `chmod`cannot change a symlink permissions.
This PR `tars` and decompresses the github workspace in order to preserve executable permissions accros build and test.
- **N/A** The added tests pass locally.
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation.
- **N/A** Applicable backports have been included in the description.
=> [23100] Preserve Workspace permissions across shared artifacts in CI
