- examples/HelloWorldExampleDS/HelloWorldPublisher.cpp
- examples/HelloWorldExampleDS/HelloWorldServer.cpp
- examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp
- examples/HelloWorldExampleDS/HelloWorld_main.cpp
solving eClock deprecation issue.
> Updating the example with new C++ features [6462]

- README.md
- examples/HelloWorldExampleDS/HelloWorldPublisher.cpp
- examples/HelloWorldExampleDS/HelloWorldPublisher.h
- examples/HelloWorldExampleDS/HelloWorldServer.cpp
- examples/HelloWorldExampleDS/HelloWorldServer.h
- examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp
- examples/HelloWorldExampleDS/HelloWorldSubscriber.h
- examples/HelloWorldExampleDS/HelloWorld_main.cpp
Update HelloWorldExampleDS to work over a network specifying:
- server IP address
- server physical port
- protocol to use: UDP or TCP.
> [7138] Update HelloworldExampleDS for network testing

- README.md
This PR updates the README.md accordingly to the Discovery Server 2.0.
> Updated README.md [9925]

- README.md
Signed-off-by: RaulSanchez <raul@eprosima.com>
> Added Python3 pandas module

- src/main.cpp
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
> Fix header backwards compatibility [10722]

- src/DSManager.cpp
- test/CMakeLists.txt
Signed-off-by: EduPonz <eduardoponz@eprosima.com>
> Add super client tests to all 2.x versions

- test/configuration/tests_params.json
- test/run_test.py
This contrains was applied to test `discovery_server_test.test_03_single_server_large.SHM_ON`
> Add shm_size contrain [11858]

- test/CMakeLists.txt
- test/configuration/test_cases/test_38_self_connection.xml
- test/configuration/test_solutions/test_38_self_connection.snapshot
- test/configuration/tests_params.json
> Add self connection test [12491]

- test/configuration/test_cases/test_33_superclient_complex.xml
> Set a higher time for complex test

- examples/HelloWorldExampleDS/HelloWorldPubSubTypes.h
- examples/HelloWorldExampleDS/HelloWorldPublisher.cpp
- examples/HelloWorldExampleDS/HelloWorldPublisher.h
- examples/HelloWorldExampleDS/HelloWorldServer.cpp
- examples/HelloWorldExampleDS/HelloWorldServer.h
- examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp
- examples/HelloWorldExampleDS/HelloWorldSubscriber.h
- examples/HelloWorldExampleDS/HelloWorld_main.cpp
- include/DI.h
- include/DSManager.h
- include/LJ.h
- src/DI.cpp
- src/DSManager.cpp
- src/LJ.cpp
- src/main.cpp
- test/configuration/test_cases/test_33_superclient_complex.xml
Removed most calls to RTPS API in favor of using their DDS API counterparts. 
Modified class names to improve readability.
> [12621] Migrate to DDS API

- test/CMakeLists.txt
> Comment super complex test till it has been studied and fixed

- test/CMakeLists.txt
> Amend xfail set typo

- CMakeLists.txt
> Add cmake options to sanitizer [16116]

- src/DiscoveryServerManager.cpp
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
> [16440] Fix compilation in Ubuntu Jammy

- include/DiscoveryServerManager.h
- src/DiscoveryServerManager.cpp
This PR depends on
* eProsima/Fast-DDS#4240
This PR updates the discovery callbacks.
> [20242] Update discovery callbacks

- .github/pull_request_template.md
- .github/workflows/mirror.yml
This PR prepared branch `3.0.x-devel` to become `master`.
- _N/A_: The added tests pass locally.
- _N/A_: Changes are backwards compatible. 
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation.
- _N/A_: Applicable backports have been included in the description.
> [20893] Prepare 3.0.x-devel to become master

- .github/workflows/mirror.yml
#81 Introduced a mirror workflow which had incorrect indentation, this PR fixes it.
- _N/A_: The added tests pass locally.
- _N/A_: Changes are backwards compatible. 
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation.
- _N/A_: Applicable backports have been included in the description.
> [20893] Fix mirror workflow YML indentation

- .github/workflows/mirror.yml
This PR adds a mirror job to 1.2.x
- _N/A_: The added tests pass locally.
- _N/A_: Changes are backwards compatible. 
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation.
- _N/A_: Applicable backports have been included in the description.
> [20893] Add mirror job 

- discovery-server.repos
This pr updates repos file for the macro version 1.x
- _N/A_ The added tests pass locally.
- _N/A_ Changes are backwards compatible. 
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.
- _N/A_ Applicable backports have been included in the description.
> [19452] Update .repos file

- discovery-server.repos
This pr updates repos file for the version 1.2.x
- N/A The added tests pass locally.
- N/A Changes are backwards compatible. 
- N/A New feature has been documented/Current behavior is correctly described in the documentation.
- N/A Applicable backports have been included in the description.
> [19452] Update repos file

- examples/HelloWorldExampleDS/HelloWorldPubSubTypes.cxx
- examples/HelloWorldExampleDS/HelloWorldPubSubTypes.hpp
- resources/static_types/HelloWorldPubSubTypes.cxx
- resources/static_types/HelloWorldPubSubTypes.hpp
This PR update the source code to new changes introduced in:
- eprosima/fast-dds-gen#375
- eprosima/fast-dds#5066
- *N/A* The added tests pass locally.
- *N/A* Changes are backwards compatible. 
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation.
- *N/A* Applicable backports have been included in the description.
> [21376] Refactor `TopicDataType`

- resources/static_types/HelloWorldPubSubTypes.cxx
- resources/static_types/HelloWorldv1.h
- **N/A** The added tests pass locally.
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation.
- **N/A** Applicable backports have been included in the description.
> Regenerate types with Fast-DDS-Gen v3.3.1

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/nightly-ubuntu-ci.yml
- CMakeLists.txt
- RELEASE_SUPPORT.md
This PR bumps version to 2.1.0 and updates related jobs and documents.
- _N/A_: The added tests pass locally.
- _N/A_: Changes are backwards compatible. 
- _N/A_: Applicable backports have been included in the description.
- _N/A_ Check CI results: changes do not issue any warning.
- _N/A_ Check CI results: failing tests are unrelated with the changes.
> [22720] Branch out 2.1.0
